### ISSUE TITLE
Task 7 rejected

### ISSUE THREAD

**Issue by e00dan** [ben-razor/crypto-funk-app#1]
Can't start application
![image](https://user-images.githubusercontent.com/4950658/130503386-64e2702e-80c8-4bc2-a466-e05b200ce737.png)

**Comment by ben-razor** [comment]
The reason for this error is that the library nervos-godwoken-integration@0.0.6 does not work with create-react-app. This is because the libary contains new Javascript features and create-react-app does not transpile imported packages.

In this submission I modified the imported nervos-godwoken-integration library to remove and rewrite Javascript features not supported by create-react-app. These modifications would not be picked up when checking out my submission and so my port would not compile.

I've now put in place a workaround where I manually copy nervos-godwoken-integration directly into my source so that it will be transpiled to a supported JS version.

A more complete solution would be for the maintainers of the nervos-godwoken-integration to transpile it to a more widely supported Javascript version before deploying it to npm. This will allow the instructions from [Port An Existing Ethereum DApp To Polyjuice](https://gitcoin.co/issue/nervosnetwork/grants/8/100026214) to work when building a front end using create-react-app.

**Comment by ben-razor** [comment]
Steps to reproduce create-react-app issue:
```bash
npx create-react-app godwoken-issue
cd ./godwoken-issue
yarn add nervos-godwoken-integration@0.0.6
```
Add the following import to App.js:
```JavaScript
import { AddressTranslator } from 'nervos-godwoken-integration';
```
```bash
yarn start
```

Should receive error:

    SyntaxError: /home/chrisb/dev/crypto/nervos/godwoken-issue/godwoken-issue/node_modules/nervos-godwoken-integration/lib/address/index.js: Support for the experimental syntax 'classProperties' isn't currently enabled (32:12):

**Comment by e00dan** [comment]
Fixed.
